### ISSUE TITLE
Duplicati protected by login password

### ISSUE THREAD

**Issue by bedge117** [wjansenw/duplicati-homeassistant#2]
I see that my Node-Red attempts to connect to my Duplicati Server.

However, I have a login password for the server.  I was hoping it was as simple as adding 
password: "passwordhere"

in the config, but no such luck.  Any Idea how to get around this?

**Comment by wjansenw** [comment]
I currently have not implemented password functionality. It looks like a relatively simple thing to implement but will need to check further.

**Comment by bedge117** [comment]
Thanks for the update.  I have authelia running, so I just disabled the password for now.

I am confused about the last commit.  I see that you removed entities because they will be available as attributes, but I am only seeing the switch and nothing else.

![image](https://github.com/wjansenw/duplicati-homeassistant/assets/77640477/6d99a08f-aab9-48a2-8539-e827b14507cb)

I am a bit confused what the purpose was and if I have this set up correctly.

**Comment by wjansenw** [comment]
I have tried to add ui-pwd functionality in this branch:
https://github.com/wjansenw/duplicati-homeassistant/tree/ui-pwd

I have only just implemented, so not yet fully tested.
Note: you might have to follow these instructions: https://primalcortex.wordpress.com/2016/05/11/node-red-and-the-crypto-js-library/
It should be possible without these instructions, but I have not managed to get these nodes to work correctly:
https://flows.nodered.org/node/node-red-contrib-crypto-js-plus

**Comment by wjansenw** [comment]
> Thanks for the update. I have authelia running, so I just disabled the password for now.
> 
> I am confused about the last commit. I see that you removed entities because they will be available as attributes, but I am only seeing the switch and nothing else.
> 
> ![image](https://private-user-images.githubusercontent.com/77640477/302498192-6d99a08f-aab9-48a2-8539-e827b14507cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTM2NDEsIm5iZiI6MTcwODM1MzM0MSwicGF0aCI6Ii83NzY0MDQ3Ny8zMDI0OTgxOTItNmQ5OWEwOGYtYWFiOS00OGEyLTg1MzktZTgyN2IxNDUwN2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE0MzU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NzNkNjgwMjZiZDdiODNhMmY4YTk0MGU0YjdjNzhmZmE4MzAzYmY0NDY4ODZiOTRjYjVjZGQ4OWEwMGU4NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ayn860nBozctdd3aMDWCo0s2Cwj9OE3xsmvkwxIklWc)
> 
> I am a bit confused what the purpose was and if I have this set up correctly.

In the switch, you will have attributes. Which you can turn into sensors if you want to expose certain information:

```
sensor:
  - platform: template
    sensors:
      duplicati_duplicati_odroid_docker_volumes_source_files_size:
        friendly_name: "Backup SourceFilesSize"
        unique_id: duplicati_mybackup_source_files_size
        value_template: "{{ state_attr('switch.duplicati_mybackup', 'Backup')['Metadata']['SourceFilesSize'] }}"
        unit_of_measurement: "B"
        device_class: data_size
```
